spring:
  rabbitmq:
#    addresses: 192.168.111.11:5672
    username: root
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    host: 192.168.111.11
    port: 5672
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
      order:
        queue:
          name: order-queue
          durable: true
        exchange:
          name: order-exchange
          durable: true
          type: topic
          ignoreDeclarationException: true
        key: order.*
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8002