spring:
  rabbitmq:
#    addresses: 192.168.111.11:5672
    username: root
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    host: 192.168.111.11
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rabbitmq_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  servlet:
    context-path: /
  port: 8001
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql